# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corr_ans', models.IntegerField(default=0)),
                ('user_name', models.CharField(max_length=100)),
                ('quest_now', models.IntegerField(default=0)),
                ('time_begin', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='votes',
        ),
        migrations.AddField(
            model_name='choice',
            name='correct',
            field=models.BooleanField(default=False),
        ),
    ]
