# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20171009_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
            ],
        ),
    ]
