# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_auto_20171011_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mas',
            name='id',
        ),
        migrations.AlterField(
            model_name='mas',
            name='id_n',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
