# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20171011_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='kol_quest',
            field=models.IntegerField(default=10),
        ),
    ]
