# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_user_kol_quest'),
    ]

    operations = [
        migrations.AddField(
            model_name='mas',
            name='num_last',
            field=models.IntegerField(default=0),
        ),
    ]
