# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-13 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_mas_num_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_fio',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
