# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-13 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_user_user_fio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.IntegerField(default=40),
        ),
    ]
