# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-14 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_user_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
