# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-15 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0016_auto_20171015_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_name',
        ),
    ]
