# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-15 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0017_remove_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
