# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-15 19:15
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0018_user_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mas_num',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=0, size=None),
            preserve_default=False,
        ),
    ]
