# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-16 12:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0019_user_mas_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mas_num',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, size=None),
        ),
    ]
