# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-16 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_auto_20171016_1548'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mas_num',
        ),
    ]
