# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-16 15:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_remove_user_mas_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mas',
        ),
    ]
